# -*- coding: utf-8 -*-
"""HW1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vQIaWSam7KlxdBKHzLvg2ofp9VPqLoZM
"""

isim = str(input("İsminiz: "))
soyisim = str(input("Soyisminiz: "))
yas = int(input("Yaşınız: "))
meslek = str(input("Mesleğiniz: "))
boy = float(input("Boyunuz: "))


print("İsim:{} ".format(isim))
print("Soyisim:{} ".format(soyisim))
print("Yas:{} ".format(yas))
print("Meslek:{}".format(meslek))
print("Boy:{}".format(boy))

print("-----------------------")

print(f"type of isim : {type(isim)} ")
print(f"type of soyisim : {type(soyisim)} ")
print(f"type of yas : {type(yas)} ")
print(f"type of meslek : {type(meslek)} ")
print(f"type of boy : {type(boy)} ")